# Generated by Django 4.2.23 on 2025-08-17 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Máximo 250 caracteres', max_length=250, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Se sugiere el texto generado por el título. Debe ser único.', max_length=60, unique=True)),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Nombre del icono de FontAwesome o similar (ej. coffee, music)', max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-id', '-pub_date'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('DRAFT', 'Draft'), ('HIDDEN', 'Hidden')], default='LIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
